package com.wordforge.ui.theme

import androidx.compose.material3.Typography
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp

// Brief calls for Bricolage Grotesque (display), Manrope (body), and
// JetBrains Mono (micro-labels) via downloadable Google Fonts. Until
// res/values/font_certs.xml is generated by Android Studio's Resource
// Manager (+ → Font → Downloadable font), wire the scale up to system
// fallbacks so the sizes/weights/spacing land immediately. Swap the
// three aliases below for GoogleFont FontFamilies when the certs land.
private val DisplayFamily = FontFamily.SansSerif   // → Bricolage Grotesque
private val BodyFamily    = FontFamily.SansSerif   // → Manrope
private val MicroFamily   = FontFamily.Monospace   // → JetBrains Mono

val Typography = Typography(
    displayLarge   = TextStyle(fontFamily = DisplayFamily, fontWeight = FontWeight.W800, fontSize = 48.sp, lineHeight = 50.sp, letterSpacing = (-1.4).sp),
    displayMedium  = TextStyle(fontFamily = DisplayFamily, fontWeight = FontWeight.W700, fontSize = 32.sp, lineHeight = 36.sp, letterSpacing = (-0.8).sp),

    headlineLarge  = TextStyle(fontFamily = DisplayFamily, fontWeight = FontWeight.W700, fontSize = 24.sp, lineHeight = 28.sp, letterSpacing = (-0.5).sp),
    headlineMedium = TextStyle(fontFamily = DisplayFamily, fontWeight = FontWeight.W700, fontSize = 22.sp, lineHeight = 26.sp, letterSpacing = (-0.4).sp),

    titleLarge     = TextStyle(fontFamily = BodyFamily,    fontWeight = FontWeight.W700, fontSize = 16.sp, lineHeight = 22.sp),
    titleMedium    = TextStyle(fontFamily = BodyFamily,    fontWeight = FontWeight.W600, fontSize = 14.sp, lineHeight = 20.sp),

    bodyLarge      = TextStyle(fontFamily = BodyFamily,    fontWeight = FontWeight.W400, fontSize = 16.sp, lineHeight = 24.sp),
    bodyMedium     = TextStyle(fontFamily = BodyFamily,    fontWeight = FontWeight.W400, fontSize = 14.sp, lineHeight = 20.sp),
    bodySmall      = TextStyle(fontFamily = BodyFamily,    fontWeight = FontWeight.W400, fontSize = 13.sp, lineHeight = 18.sp),

    labelLarge     = TextStyle(fontFamily = MicroFamily,   fontWeight = FontWeight.W500, fontSize = 12.sp, lineHeight = 16.sp, letterSpacing = 1.5.sp),
    labelMedium    = TextStyle(fontFamily = MicroFamily,   fontWeight = FontWeight.W500, fontSize = 11.sp, lineHeight = 14.sp, letterSpacing = 1.4.sp),
    labelSmall     = TextStyle(fontFamily = MicroFamily,   fontWeight = FontWeight.W500, fontSize = 10.sp, lineHeight = 13.sp, letterSpacing = 0.4.sp),
)
